name: Create-COnsume Artifact

on:
  workflow_dispatch:

jobs:
  CREATE-ARTIFACT:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact
        run: |
          echo "Random AF" > Artifact.txt
          echo "Chao AF" >> Artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestArtifact
          path: Artifact.txt

  CONSUME-ARTIFACT:
    runs-on: ubuntu-latest
    needs: [ CREATE-ARTIFACT ] 
    steps:
      - name: Download-Artifact
        uses: actions/download-artifact@v4
        with:
          name: TestArtifact
        
      - name: Read Artifact
        run: cat Artifact.txt
            
